version: '3.5'
networks:
  default:
    name: tf.local

services:
  tensorflow:
    container_name: 'tf'
    hostname: 'train.tf.local'
    build: "."
    ports:
     - "8888:8888"
     - "6006:6006"
    volumes:
     - ./data:/data
     - ./images:/images
     - ./models:/models
     - ./zoo_models:/zoo_models
     - ./sh:/sh
