version: '3.5'
networks:
  default:
    name: tf.local

services:
  tensorflow:
    container_name: tf
    hostname: train.tf.local
    build: "."
    ports:
     - "8888:8888"
     - "6006:6006"
    volumes:
     - ./data:/data
     - ./images:/images
     - ./models:/models
     - ./zoo_models:/zoo_models
     - ./sh:/sh
  tf-serving:
    container_name: tf-serving
    image: tensorflow/serving:1.12.0
    hostname: tf-serving.local
    ports:
      - 8501:8501
      - 8500:8500
    volumes:
      - ./models:/models
    env_file:
    - tf-serving.env